services:
    postgres:
        image: postgres:15-alpine
        restart: always
        env_file:
            - .env
        ports:
            - "${POSTGRES_DB_PORT}:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - ecommerce-network

    minio:
        image: minio/minio
        restart: always
        command: server /data --console-address ":9001"
        env_file:
            - .env
        ports:
            - "${MINIO_API_PORT}:9000"
            - "${MINIO_UI_PORT}:9001"
        volumes:
            - minio_data:/data
        healthcheck:
            test: ["CMD", "mc", "ready", "local"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - ecommerce-network

    api:
        image: ${DOCKERHUB_USERNAME}/ecommerce-api:latest
        restart: always
        env_file:
            - .env
        ports:
            - "${API_PORT}:${APP_PORT}"
        depends_on:
            - postgres
            - minio
        networks:
            - ecommerce-network

volumes:
    pgdata:
    minio_data:

networks:
    ecommerce-network:
        name: ecommerce-network
        driver: bridge
